<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Framework" Version="17.8.27" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.8.27" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Tasks\**\*.cs">
      <DependentUpon></DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="ServicePlugin.Packaging.props" Pack="true" PackagePath="build" />
    <None Include="ServicePlugin.Packaging.targets" Pack="true" PackagePath="build" />
  </ItemGroup>
</Project>
