name: .NET 8.0 Desktop Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: windows-latest   # Needed for .NET Desktop SDK
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore dependencies
        run: dotnet restore DesktopApplicationTemplate.sln

      - name: Build solution
        run: dotnet build DesktopApplicationTemplate.sln --configuration Release -bl:build.binlog

      - name: Run unit tests
        run: dotnet test DesktopApplicationTemplate.sln --configuration Release --no-build --logger "trx;LogFileName=test_results.trx" --results-directory TestResults
        continue-on-error: true

      - name: Upload build and test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-test-artifacts
          path: |
            build.binlog
            TestResults

      - name: Comment on test failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ Unit tests failed. Review artifacts for details: ${runUrl}`
            });

      - name: Fail if tests failed
        if: failure()
        run: exit 1
