name: Self Heal

on:
  workflow_run:
    workflows: ['.NET 8.0 Desktop CI/CD']
    types:
      - completed

jobs:
  self-heal:
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.head_branch == 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
      - name: Download self-heal state
        uses: actions/download-artifact@v4
        with:
          name: codex-selfheal-state
          path: .codex-selfheal
        continue-on-error: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests PyGithub openai
      - name: Run Codex repair
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python tools/selfheal/repair_with_codex.py
      - name: Upload self-heal state
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codex-selfheal-state
          path: .codex-selfheal/state.json
